"""add mic_code to markets

Revision ID: 115d39936229
Revises: 7d72dfc9d18b
Create Date: 2025-11-19 20:05:31.930101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115d39936229'
down_revision: Union[str, None] = '7d72dfc9d18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_company_notes_monitoring_triggers_gin', table_name='company_notes', postgresql_using='gin')
    op.drop_index('idx_company_notes_tags_gin', table_name='company_notes', postgresql_using='gin')
    op.add_column('markets', sa.Column('mic_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'mic_code')
    op.create_index('idx_company_notes_tags_gin', 'company_notes', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_company_notes_monitoring_triggers_gin', 'company_notes', ['monitoring_triggers'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
