"""Fix portfolios timestamps

Revision ID: 19930fed3089
Revises: 331013565bcc
Create Date: 2025-05-10 16:02:55.987385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19930fed3089'
down_revision: Union[str, None] = '331013565bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_id', table_name='positions')
    op.drop_table('positions')
    op.add_column('favorite_stocks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_favorite_stocks_id', table_name='favorite_stocks')
    op.create_unique_constraint(None, 'favorite_stocks', ['user_id', 'company_id'])
    op.add_column('portfolio_positions', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.drop_index('ix_portfolio_positions_id', table_name='portfolio_positions')
    op.create_unique_constraint(None, 'portfolio_positions', ['portfolio_id', 'company_id'])
    op.add_column('transactions', sa.Column('fee', sa.Numeric(precision=18, scale=4), nullable=False))
    op.alter_column('transactions', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_transactions_id', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    op.alter_column('transactions', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'fee')
    op.drop_constraint(None, 'portfolio_positions', type_='unique')
    op.create_index('ix_portfolio_positions_id', 'portfolio_positions', ['id'], unique=False)
    op.drop_column('portfolio_positions', 'last_updated')
    op.drop_constraint(None, 'favorite_stocks', type_='unique')
    op.create_index('ix_favorite_stocks_id', 'favorite_stocks', ['id'], unique=False)
    op.drop_column('favorite_stocks', 'created_at')
    op.create_table('positions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shares', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='positions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='positions_pkey')
    )
    op.create_index('ix_positions_id', 'positions', ['id'], unique=False)
    # ### end Alembic commands ###
