"""add is_visible and unique name

Revision ID: 343016a8669d
Revises: ed22bc68a3b6
Create Date: 2026-01-31 09:09:01.720391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '343016a8669d'
down_revision: Union[str, None] = 'ed22bc68a3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_instruments_figi'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_isin'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_type'), table_name='instruments')
    op.drop_table('instruments')
    op.add_column('baskets', sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False))
    op.create_unique_constraint('uq_basket_name_owner', 'baskets', ['name', 'owner_id'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_basket_name_owner', 'baskets', type_='unique')
    op.drop_column('baskets', 'is_visible')
    op.create_table('instruments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('stock', 'etf', 'bond', 'crypto', 'commodity', 'cash', name='instrumenttype'), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('market_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isin', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('figi', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.market_id'], name=op.f('instruments_market_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('instruments_pkey')),
    sa.UniqueConstraint('symbol', 'market_id', name=op.f('uq_instrument_symbol_market'))
    )
    op.create_index(op.f('ix_instruments_type'), 'instruments', ['type'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_index(op.f('ix_instruments_isin'), 'instruments', ['isin'], unique=False)
    op.create_index(op.f('ix_instruments_figi'), 'instruments', ['figi'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alert_type', postgresql.ENUM('PRICE_ABOVE', 'PRICE_BELOW', 'PERCENT_CHANGE_UP', 'PERCENT_CHANGE_DOWN', 'sma_50_above_sma_200', 'sma_50_below_sma_200', 'sma_50_approaching_sma_200', 'SMA_50_ABOVE_SMA_200', 'SMA_50_BELOW_SMA_200', 'SMA_50_APPROACHING_SMA_200', name='alerttype'), autoincrement=False, nullable=False),
    sa.Column('threshold_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_triggered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('snoozed_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('alerts_company_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('alerts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    # ### end Alembic commands ###
