"""Add invitation-user relationship

Revision ID: 60fc79426bf2
Revises: 62cde511ff60
Create Date: 2025-04-05 19:11:44.142577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fc79426bf2'
down_revision: Union[str, None] = '62cde511ff60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitations', 'max_uses',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invitations', 'used_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_invitations_code', table_name='invitations')
    op.drop_index('ix_invitations_id', table_name='invitations')
    op.create_unique_constraint(None, 'invitations', ['code'])
    op.add_column('users', sa.Column('invitation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'invitations', ['invitation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invitation_id')
    op.drop_constraint(None, 'invitations', type_='unique')
    op.create_index('ix_invitations_id', 'invitations', ['id'], unique=False)
    op.create_index('ix_invitations_code', 'invitations', ['code'], unique=True)
    op.alter_column('invitations', 'used_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invitations', 'max_uses',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
