"""Initial baseline~

Revision ID: 786a6168de29
Revises: 
Create Date: 2025-11-04 12:18:01.074315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '786a6168de29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_indexes')
    op.drop_index('ix_historical_data_nasdaq_date', table_name='historical_data_nasdaq')
    op.drop_table('historical_data_nasdaq')
    op.drop_index('ix_historical_data_cac_date', table_name='historical_data_cac')
    op.drop_table('historical_data_cac')
    op.drop_index('ix_positions_id', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_historicaldata_date', table_name='historical_data')
    op.drop_index('ix_historical_data_date', table_name='historical_data')
    op.drop_table('historical_data')
    op.drop_index('ix_historical_data_sp500_date', table_name='historical_data_sp500')
    op.drop_table('historical_data_sp500')
    op.drop_table('company_market_association')
    op.drop_index('ix_historical_data_dowjones_date', table_name='historical_data_dowjones')
    op.drop_table('historical_data_dowjones')
    op.drop_index('ix_historical_data_wse_date', table_name='historical_data_wse')
    op.drop_table('historical_data_wse')
    op.alter_column('companies', 'market_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Replace it later with stock_indexes association table',
               existing_nullable=True)
    op.add_column('favorite_stocks', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint('uq_favorite_stocks_user_company', 'favorite_stocks', ['user_id', 'company_id'])
    op.add_column('portfolio_positions', sa.Column('last_updated', sa.DateTime(), nullable=False))
    op.create_unique_constraint('uq_portfolio_positions_portfolio_company', 'portfolio_positions', ['portfolio_id', 'company_id'])
    op.add_column('portfolios', sa.Column('currency', sa.String(length=3), nullable=False, server_default='USD'))
    op.add_column('transactions', sa.Column('fee', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('transactions', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('transactions', sa.Column('currency_rate', sa.Numeric(precision=18, scale=6), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'currency_rate')
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'fee')
    op.drop_column('portfolios', 'currency')
    op.drop_constraint('uq_portfolio_positions_portfolio_company', 'portfolio_positions', type_='unique')
    op.drop_column('portfolio_positions', 'last_updated')
    op.drop_constraint('uq_favorite_stocks_user_company', 'favorite_stocks', type_='unique')
    op.drop_column('favorite_stocks', 'created_at')
    op.alter_column('companies', 'market_id',
               existing_type=sa.INTEGER(),
               comment='Replace it later with stock_indexes association table',
               existing_nullable=True)
    op.create_table('historical_data_wse',
    sa.Column('data_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adjusted_close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='historical_data_wse_company_id_fkey'),
    sa.PrimaryKeyConstraint('data_id', name='historical_data_wse_pkey')
    )
    op.create_index('ix_historical_data_wse_date', 'historical_data_wse', ['date'], unique=False)
    op.create_table('historical_data_dowjones',
    sa.Column('data_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adjusted_close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='historical_data_dowjones_company_id_fkey'),
    sa.PrimaryKeyConstraint('data_id', name='historical_data_dowjones_pkey')
    )
    op.create_index('ix_historical_data_dowjones_date', 'historical_data_dowjones', ['date'], unique=False)
    op.create_table('company_market_association',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('market_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='company_market_association_company_id_fkey'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.market_id'], name='company_market_association_market_id_fkey'),
    sa.PrimaryKeyConstraint('company_id', 'market_id', name='company_market_association_pkey')
    )
    op.create_table('historical_data_sp500',
    sa.Column('data_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adjusted_close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='historical_data_sp500_company_id_fkey'),
    sa.PrimaryKeyConstraint('data_id', name='historical_data_sp500_pkey')
    )
    op.create_index('ix_historical_data_sp500_date', 'historical_data_sp500', ['date'], unique=False)
    op.create_table('historical_data',
    sa.Column('data_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adjusted_close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='historical_data_company_id_fkey'),
    sa.PrimaryKeyConstraint('data_id', name='historical_data_pkey'),
    sa.UniqueConstraint('company_id', 'date', name='_company_date_uc')
    )
    op.create_index('ix_historical_data_date', 'historical_data', ['date'], unique=False)
    op.create_index('idx_historicaldata_date', 'historical_data', ['date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shares', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('average_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='positions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='positions_pkey')
    )
    op.create_index('ix_positions_id', 'positions', ['id'], unique=False)
    op.create_table('historical_data_cac',
    sa.Column('data_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adjusted_close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='historical_data_cac_company_id_fkey'),
    sa.PrimaryKeyConstraint('data_id', name='historical_data_cac_pkey')
    )
    op.create_index('ix_historical_data_cac_date', 'historical_data_cac', ['date'], unique=False)
    op.create_table('historical_data_nasdaq',
    sa.Column('data_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adjusted_close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='historical_data_nasdaq_company_id_fkey'),
    sa.PrimaryKeyConstraint('data_id', name='historical_data_nasdaq_pkey')
    )
    op.create_index('ix_historical_data_nasdaq_date', 'historical_data_nasdaq', ['date'], unique=False)
    op.create_table('company_indexes',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('index_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='company_indexes_company_id_fkey'),
    sa.ForeignKeyConstraint(['index_id'], ['stock_indexes.index_id'], name='company_indexes_index_id_fkey'),
    sa.PrimaryKeyConstraint('company_id', 'index_id', name='company_indexes_pkey')
    )
    # ### end Alembic commands ###
