"""Remove derived financial metrics from CompanyFinancials

Revision ID: 87eda14c10b2
Revises: eed835149bd6
Create Date: 2025-03-25 17:59:04.581524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87eda14c10b2'
down_revision: Union[str, None] = 'eed835149bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financial_history', sa.Column('enterprise_value', sa.Float(), nullable=True))
    op.add_column('company_financial_history', sa.Column('gross_profit', sa.Float(), nullable=True))
    op.add_column('company_financial_history', sa.Column('earnings_growth', sa.Float(), nullable=True))
    op.add_column('company_financial_history', sa.Column('revenue_growth', sa.Float(), nullable=True))
    op.add_column('company_financials', sa.Column('operating_income', sa.Float(), nullable=True))
    op.drop_column('company_financials', 'operating_margins')
    op.drop_column('company_financials', 'revenue_growth')
    op.drop_column('company_financials', 'return_on_equity')
    op.drop_column('company_financials', 'profit_margins')
    op.drop_column('company_financials', 'gross_margins')
    op.drop_column('company_financials', 'return_on_assets')
    op.drop_column('company_financials', 'earnings_growth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financials', sa.Column('earnings_growth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('company_financials', sa.Column('return_on_assets', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('company_financials', sa.Column('gross_margins', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('company_financials', sa.Column('profit_margins', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('company_financials', sa.Column('return_on_equity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('company_financials', sa.Column('revenue_growth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('company_financials', sa.Column('operating_margins', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('company_financials', 'operating_income')
    op.drop_column('company_financial_history', 'revenue_growth')
    op.drop_column('company_financial_history', 'earnings_growth')
    op.drop_column('company_financial_history', 'gross_profit')
    op.drop_column('company_financial_history', 'enterprise_value')
    # ### end Alembic commands ###
