"""add_isin_to_companies

Revision ID: a053e3ff0ea8
Revises: 6f1a2b3c4d5e
Create Date: 2025-11-30 17:18:27.226447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a053e3ff0ea8'
down_revision: Union[str, None] = '6f1a2b3c4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('isin', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_isin'), 'companies', ['isin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_isin'), table_name='companies')
    op.drop_column('companies', 'isin')
    # ### end Alembic commands ###
