"""remove company_market_association

Revision ID: d2d77d0343c5
Revises: d5d0c01e1017
Create Date: 2025-06-06 12:12:00.895162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d77d0343c5'
down_revision: Union[str, None] = 'd5d0c01e1017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_market_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_market_association',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('market_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('company_market_association_company_id_fkey')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.market_id'], name=op.f('company_market_association_market_id_fkey')),
    sa.PrimaryKeyConstraint('company_id', 'market_id', name=op.f('company_market_association_pkey'))
    )
    # ### end Alembic commands ###
