"""add_smart_baskets

Revision ID: ed22bc68a3b6
Revises: 5013fc27cb14
Create Date: 2026-01-07 16:39:16.321678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed22bc68a3b6'
down_revision: Union[str, None] = '5013fc27cb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing accidental drops of other tables
    op.add_column('baskets', sa.Column('rules', sa.JSON(), nullable=True))
    
    # Data Seeding
    baskets_table = sa.table(
        'baskets',
        sa.Column('name', sa.String),
        sa.Column('type', sa.Enum('MARKET', 'INDEX', 'PORTFOLIO', 'FAVORITES', 'CUSTOM', name='baskettype')),
        sa.Column('rules', sa.JSON),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()) # Though server_default handles it in DB, bulk_insert might need it if not omitted? usually ok.
    )

    op.bulk_insert(
        baskets_table,
        [
            {"name": "NYSE", "type": "MARKET", "rules": {"market_codes": ["XNYS"]}},
            {"name": "NASDAQ", "type": "MARKET", "rules": {"market_codes": ["XNAS"]}},
            {"name": "Polish Market (GPW)", "type": "MARKET", "rules": {"market_codes": ["XWAR"]}},
            {"name": "European Growth", "type": "MARKET", "rules": {"market_codes": ["XETR", "XAMS", "XPAR", "XLON"], "exclude_symbols": ["TL0.DE"]}},
            {"name": "Speculative / Small Cap", "type": "MARKET", "rules": {"market_codes": ["XASE", "NGM", "XARCA"]}},
            {"name": "Delisted / OTC", "type": "MARKET", "rules": {"market_codes": ["DELISTED", "YHD"]}},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baskets', 'rules')
    # Use execute to delete seeded data if needed, but usually schema downgrade is enough (column gone = data gone)
    # ### end Alembic commands ###
