"""Add created_at column to fx_rates

Revision ID: ef660bac66fd
Revises: bcfbadac87d8
Create Date: 2025-06-08 10:21:15.105209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef660bac66fd'
down_revision: Union[str, None] = 'bcfbadac87d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fx_rates_date'), table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quote_currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fx_rates_pkey')),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'date', name=op.f('_fxrate_uc'))
    )
    op.create_index(op.f('ix_fx_rates_date'), 'fx_rates', ['date'], unique=False)
    # ### end Alembic commands ###
