"""Add shares_outstanding  to financial tables

Revision ID: 01d55e4b31a6
Revises: 1b7f48a9f216
Create Date: 2025-03-27 16:37:05.875228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d55e4b31a6'
down_revision: Union[str, None] = '1b7f48a9f216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financial_history', sa.Column('shares_outstanding', sa.BigInteger(), nullable=True))
    op.add_column('company_financials', sa.Column('shares_outstanding', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_financials', 'shares_outstanding')
    op.drop_column('company_financial_history', 'shares_outstanding')
    # ### end Alembic commands ###
