"""Add cash_and_cash_equivalents to financial models

Revision ID: 1b7f48a9f216
Revises: 89f64ac9bbf6
Create Date: 2025-03-27 16:28:43.816588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7f48a9f216'
down_revision: Union[str, None] = '89f64ac9bbf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financial_history', sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=True))
    op.add_column('company_financials', sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_financials', 'cash_and_cash_equivalents')
    op.drop_column('company_financial_history', 'cash_and_cash_equivalents')
    # ### end Alembic commands ###
