"""Add created_at to StockPriceHistory

Revision ID: 331013565bcc
Revises: 1ba1f90825af
Create Date: 2025-04-11 13:38:15.318900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331013565bcc'
down_revision: Union[str, None] = '1ba1f90825af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('stock_price_history', sa.Column('created_at', sa.DateTime(), nullable=True))

    # Step 2: Backfill with a fixed old timestamp
    op.execute("""
        UPDATE stock_price_history SET created_at = '1900-01-01 00:00:00'
    """)

    # Step 3: Alter column to be non-nullable
    op.alter_column('stock_price_history', 'created_at', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_price_history', 'created_at')
    # ### end Alembic commands ###
