"""Add TRANSFER_* to TxType; drop cash_balances

Revision ID: 53c2e5c671bf
Revises: 786a6168de29
Create Date: 2025-11-04 14:13:48.337407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53c2e5c671bf'
down_revision: Union[str, None] = '786a6168de29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cash_balances_id', table_name='cash_balances')
    op.drop_table('cash_balances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_balances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='cash_balances_portfolio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cash_balances_pkey')
    )
    op.create_index('ix_cash_balances_id', 'cash_balances', ['id'], unique=False)
    # ### end Alembic commands ###
