"""Add dividends_paid to CompanyFinancials

Revision ID: 593bdf662ce2
Revises: 01d55e4b31a6
Create Date: 2025-03-29 07:52:20.495074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593bdf662ce2'
down_revision: Union[str, None] = '01d55e4b31a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financial_history', sa.Column('dividends_paid', sa.Float(), nullable=True))
    op.add_column('company_financials', sa.Column('dividends_paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_financials', 'dividends_paid')
    op.drop_column('company_financial_history', 'dividends_paid')
    # ### end Alembic commands ###
