"""Add invitation-user relationship

Revision ID: 60fc79426bf2
Revises: 62cde511ff60
Create Date: 2025-04-05 19:11:44.142577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fc79426bf2'
down_revision: Union[str, None] = '62cde511ff60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('favorite_stocks')]

    if 'company_id' not in columns:
        op.add_column('favorite_stocks', sa.Column('company_id', sa.Integer(), nullable=False))
        op.create_foreign_key(None, 'favorite_stocks', 'companies', ['company_id'], ['company_id'])
    else:
        print("⚠️  Skipping: 'company_id' already exists in favorite_stocks")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invitation_id')
    op.drop_constraint(None, 'invitations', type_='unique')
    op.create_index('ix_invitations_id', 'invitations', ['id'], unique=False)
    op.create_index('ix_invitations_code', 'invitations', ['code'], unique=True)
    op.alter_column('invitations', 'used_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invitations', 'max_uses',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
