"""Add debt column to CompanyFinancials and CompanyFinancialHistory

Revision ID: 89f64ac9bbf6
Revises: fa9bffc6d3c6
Create Date: 2025-03-27 16:13:17.974731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f64ac9bbf6'
down_revision: Union[str, None] = 'fa9bffc6d3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financial_history', sa.Column('total_debt', sa.Float(), nullable=True))
    op.add_column('company_financials', sa.Column('total_debt', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_financials', 'total_debt')
    op.drop_column('company_financial_history', 'total_debt')
    # ### end Alembic commands ###
