"""Add current_price to CompanyFinancials

Revision ID: fa9bffc6d3c6
Revises: 87eda14c10b2
Create Date: 2025-03-27 14:50:19.020080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa9bffc6d3c6'
down_revision: Union[str, None] = '87eda14c10b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financials', sa.Column('current_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_financials', 'current_price')
    # ### end Alembic commands ###
